import { AppSidebar } from "@/components/app-sidebar";
import ParentComponent from "@/components/ParentDashLayout";
import { Breadcrumb, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbPage, BreadcrumbSeparator } from "@/components/ui/breadcrumb";
import { Button } from "@/components/ui/button";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { Separator } from "@radix-ui/react-separator";
import { Bell, MessageCircle } from "lucide-react";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
    const msg = [{}, {}]
    return (
        <html lang="en">
            <body>
                <ParentComponent>
                    {children}
                </ParentComponent>
            </body>
        </html>
    );
}
